class ClubDetail {
  final String id;
  final String name;
  final String subtitle;
  final String founded;
  final String stadium;
  final String style;
  final List<String> roster;
  final String imagePath;

  const ClubDetail({
    required this.id,
    required this.name,
    required this.subtitle,
    required this.founded,
    required this.stadium,
    required this.style,
    required this.roster,
    required this.imagePath,
  });
}

// Data Mapping based on User Input and previous Image Ordering
// 0. Real Madrid (8f31...)
// 1. Newcastle (cc85...)
// 2. Man Utd (f713...)
// 3. Man City (09b1...)
// 4. Liverpool (bde1...)
// 5. LAFC (0d2d...)
// 6. LA Galaxy (c9bf...)
// 7. Inter Miami (912b...)
// 8. Barcelona (205b...)
// 9. Arsenal (9344...)

const List<ClubDetail> clubData = [
  ClubDetail(
    id: '0',
    name: 'Real Madrid',
    subtitle: 'Spain – La Liga',
    founded: '1902',
    stadium: 'Santiago Bernabéu',
    style: 'Elite, attacking, Champions League specialists',
    imagePath: 'assets/Real Madrid.jpg',
    roster: [
      'Thibaut Courtois (GK)',
      'Dani Carvajal (DF)',
      'Éder Militão (DF)',
      'David Alaba (DF)',
      'Antonio Rüdiger (DF)',
      'Jude Bellingham (MF)',
      'Eduardo Camavinga (MF)',
      'Aurélien Tchouaméni (MF)',
      'Federico Valverde (MF)',
      'Vinícius Jr. (FW)',
      'Rodrygo (FW)',
      'Kylian Mbappé (FW)',
    ],
  ),
  ClubDetail(
    id: '1',
    name: 'Newcastle United',
    subtitle: 'England – Premier League',
    founded: '1892',
    stadium: 'St James’ Park',
    style: 'Physical, high-energy, pressing',
    imagePath: 'assets/New Castle.jpg',
    roster: [
      'Nick Pope (GK)',
      'Kieran Trippier (DF)',
      'Sven Botman (DF)',
      'Fabian Schär (DF)',
      'Dan Burn (DF)',
      'Bruno Guimarães (MF)',
      'Joelinton (MF)',
      'Sandro Tonali (MF)',
      'Anthony Gordon (FW)',
      'Alexander Isak (FW)',
      'Callum Wilson (FW)',
    ],
  ),
  ClubDetail(
    id: '2',
    name: 'Manchester United',
    subtitle: 'England – Premier League',
    founded: '1878',
    stadium: 'Old Trafford',
    style: 'Fast transitions, youth + stars',
    imagePath: 'assets/Manchester United.jpg',
    roster: [
      'André Onana (GK)',
      'Diogo Dalot (DF)',
      'Lisandro Martínez (DF)',
      'Raphaël Varane (DF)',
      'Luke Shaw (DF)',
      'Casemiro (MF)',
      'Bruno Fernandes (MF)',
      'Kobbie Mainoo (MF)',
      'Marcus Rashford (FW)',
      'Alejandro Garnacho (FW)',
      'Rasmus Højlund (FW)',
    ],
  ),
  ClubDetail(
    id: '3',
    name: 'Manchester City',
    subtitle: 'England – Premier League',
    founded: '1880',
    stadium: 'Etihad Stadium',
    style: 'Possession-based, tactical dominance',
    imagePath: 'assets/Manchester City.jpg',
    roster: [
      'Ederson (GK)',
      'Kyle Walker (DF)',
      'Rúben Dias (DF)',
      'John Stones (DF)',
      'Joško Gvardiol (DF)',
      'Rodri (MF)',
      'Kevin De Bruyne (MF)',
      'Bernardo Silva (MF)',
      'Phil Foden (MF)',
      'Erling Haaland (FW)',
      'Julián Álvarez (FW)',
    ],
  ),
  ClubDetail(
    id: '4',
    name: 'Liverpool',
    subtitle: 'England – Premier League',
    founded: '1892',
    stadium: 'Anfield',
    style: 'Intense pressing, fast attacks',
    imagePath: 'assets/Liverpool.jpg',
    roster: [
      'Alisson Becker (GK)',
      'Trent Alexander-Arnold (DF)',
      'Virgil van Dijk (DF)',
      'Ibrahima Konaté (DF)',
      'Andrew Robertson (DF)',
      'Alexis Mac Allister (MF)',
      'Dominik Szoboszlai (MF)',
      'Curtis Jones (MF)',
      'Mohamed Salah (FW)',
      'Darwin Núñez (FW)',
      'Luis Díaz (FW)',
    ],
  ),
  ClubDetail(
    id: '5',
    name: 'LAFC',
    subtitle: 'USA – MLS',
    founded: '2014',
    stadium: 'BMO Stadium',
    style: 'Fast, aggressive, modern MLS power',
    imagePath: 'assets/LAFC.jpg',
    roster: [
      'Hugo Lloris (GK)',
      'Jesús Murillo (DF)',
      'Giorgio Chiellini (DF)',
      'Ryan Hollingshead (DF)',
      'Ilie Sánchez (MF)',
      'Kellyn Acosta (MF)',
      'Eduard Atuesta (MF)',
      'Carlos Vela (FW)',
      'Denis Bouanga (FW)',
      'Cristian Olivera (FW)',
    ],
  ),
  ClubDetail(
    id: '6',
    name: 'LA Galaxy',
    subtitle: 'USA – MLS',
    founded: '1994',
    stadium: 'Dignity Health Sports Park',
    style: 'Star-driven, attacking',
    imagePath: 'assets/LA Galaxy.jpg',
    roster: [
      'John McCarthy (GK)',
      'Maya Yoshida (DF)',
      'Martín Cáceres (DF)',
      'Mark Delgado (MF)',
      'Gastón Brugman (MF)',
      'Riqui Puig (MF)',
      'Diego Fagúndez (FW)',
      'Joseph Paintsil (FW)',
      'Dejan Joveljić (FW)',
    ],
  ),
  ClubDetail(
    id: '7',
    name: 'Inter Miami',
    subtitle: 'USA – MLS',
    founded: '2018',
    stadium: 'DRV PNK Stadium',
    style: 'Technical, star-focused',
    imagePath: 'assets/Inter Miami.jpg',
    roster: [
      'Drake Callender (GK)',
      'Jordi Alba (DF)',
      'DeAndre Yedlin (DF)',
      'Sergio Busquets (MF)',
      'Benjamin Cremaschi (MF)',
      'Lionel Messi (FW)',
      'Luis Suárez (FW)',
      'Robert Taylor (FW)',
      'Leonardo Campana (FW)',
    ],
  ),
  ClubDetail(
    id: '8',
    name: 'Barcelona',
    subtitle: 'Spain – La Liga',
    founded: '1899',
    stadium: 'Spotify Camp Nou',
    style: 'Tiki-taka, youth development',
    imagePath: 'assets/Barcelona.jpg',
    roster: [
      'Marc-André ter Stegen (GK)',
      'Ronald Araújo (DF)',
      'Jules Koundé (DF)',
      'Alejandro Balde (DF)',
      'Frenkie de Jong (MF)',
      'Pedri (MF)',
      'Gavi (MF)',
      'İlkay Gündoğan (MF)',
      'Lamine Yamal (FW)',
      'Robert Lewandowski (FW)',
      'Raphinha (FW)',
    ],
  ),
  ClubDetail(
    id: '9',
    name: 'Arsenal',
    subtitle: 'England – Premier League',
    founded: '1886',
    stadium: 'Emirates Stadium',
    style: 'Technical, structured, attacking',
    imagePath: 'assets/Arsenal.jpg',
    roster: [
      'David Raya (GK)',
      'Ben White (DF)',
      'William Saliba (DF)',
      'Gabriel Magalhães (DF)',
      'Oleksandr Zinchenko (DF)',
      'Declan Rice (MF)',
      'Martin Ødegaard (MF)',
      'Kai Havertz (MF)',
      'Bukayo Saka (FW)',
      'Gabriel Martinelli (FW)',
      'Gabriel Jesus (FW)',
    ],
  ),
];
