// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJetgxOJ8HrFqsTAvspJjf-JfPBzKP2mI',
    appId: '1:419773772378:web:06e9157e95b39ed92d1e63',
    messagingSenderId: '419773772378',
    projectId: 'ellazo-footballclub',
    authDomain: 'ellazo-footballclub.firebaseapp.com',
    databaseURL: 'https://ellazo-footballclub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ellazo-footballclub.appspot.com',
    measurementId: 'G-T6F4D3P6KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeVtjusSL2zhrlIyaNjHanW3AVvWDzNZI',
    appId: '1:419773772378:android:b46a98909dd287212d1e63',
    messagingSenderId: '419773772378',
    projectId: 'ellazo-footballclub',
    databaseURL: 'https://ellazo-footballclub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ellazo-footballclub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYw4yu9TGVKP4Wy52f0yqklfjt6wJVG_8',
    appId: '1:419773772378:ios:faeb9600313602792d1e63',
    messagingSenderId: '419773772378',
    projectId: 'ellazo-footballclub',
    databaseURL: 'https://ellazo-footballclub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ellazo-footballclub.appspot.com',
    iosBundleId: 'com.example.tmFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYw4yu9TGVKP4Wy52f0yqklfjt6wJVG_8',
    appId: '1:419773772378:ios:faeb9600313602792d1e63',
    messagingSenderId: '419773772378',
    projectId: 'ellazo-footballclub',
    databaseURL: 'https://ellazo-footballclub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ellazo-footballclub.appspot.com',
    iosBundleId: 'com.example.tmFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJetgxOJ8HrFqsTAvspJjf-JfPBzKP2mI',
    appId: '1:419773772378:web:b11d2212274ea9542d1e63',
    messagingSenderId: '419773772378',
    projectId: 'ellazo-footballclub',
    authDomain: 'ellazo-footballclub.firebaseapp.com',
    databaseURL: 'https://ellazo-footballclub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ellazo-footballclub.appspot.com',
    measurementId: 'G-SBBQHC41EQ',
  );

}
